### ISSUE TITLE
DELETE route - passing the garden ID but not working

### ISSUE THREAD

**Issue by lauramparker** [lauramparker/GardenGrow_Project3#59]
DELETE Route is in MyGardens.js.  (supporting component ListGroup where delete buttons exists)
 Currently passing the garden id when delete button clicked but error is 422 "unprocessable Entity". 
 route example:
 http://localhost:3000/api/gardens/605e6f230cdfe6b454d8e9d4

**Comment by jesusefraingonzalez** [comment]
Delete routes now working fine and are also being removed from the dom
